/*
  The unavoidable C shim.

  Most of the Lean runtime API a host needs -- lean_inc, lean_dec, lean_dec_ref,
  lean_io_mk_world, lean_io_result_is_ok, lean_string_cstr -- is `static inline`
  in lean.h and therefore has NO linkable symbol.  Rust cannot `extern "C"` any
  of it, and bindgen cannot help: inline functions have no symbol to bind.  Every
  Rust<->Lean integration needs a file like this one.  It is small and stable,
  but it is not zero, and it is permanent.

  Nothing here lets a `lean_object*` escape into Rust.  That is deliberate: the
  FFI spike SIGSEGV'd in 3 of 5 runs when one `lean_object*` was shared across 8
  threads without `lean_mark_mt`.  With a String -> String boundary there is
  nothing to share and nothing to get wrong.
*/
#include <lean/lean.h>
#include <stdlib.h>
#include <string.h>

/* Not declared in ANY public header.  Lean emits the call into its own
   generated `main`, which is why it is easy to miss. */
LEAN_EXPORT void lean_initialize_runtime_module(void);

/* Generated by Lean for the root module.  The symbol embeds the Lake package
   name; find it with `nm`, do not guess it. */
LEAN_EXPORT lean_object *initialize_TmKernel_TmKernel(uint8_t builtin, lean_object *w);

/* The kernel's single export. */
LEAN_EXPORT lean_object *tm_kernel_call(lean_object *input);

static int tm_ready = 0;

int tm_kernel_init(void) {
  if (tm_ready) return 0;
  lean_initialize_runtime_module();
  /* A Lean panic otherwise returns Inhabited.default with exit code 0 -- a
     silent wrong answer.  `true` here would be a hard exit(1) with no unwind,
     which leaves a ratatui terminal in raw mode.  Neither is acceptable, so the
     kernel is total instead (CI greps for `partial`, `!`, `panic!`,
     `native_decide`, `sorry`, `.toOption`) and this stays false: a fault then
     shows up as a response Rust cannot parse, which it reports as a bug. */
  lean_set_exit_on_panic(false);
  lean_object *res = initialize_TmKernel_TmKernel(1 /* builtin */, lean_io_mk_world());
  if (!lean_io_result_is_ok(res)) {
    lean_io_result_show_error(res);
    lean_dec(res);
    return 1;
  }
  lean_dec_ref(res);
  lean_io_mark_end_initialization();
  tm_ready = 1;
  return 0;
}

/* Owns nothing on entry, owns nothing on exit: the result is copied out with
   strdup and the Lean object is dropped before returning. */
char *tm_kernel_call_c(const char *req) {
  lean_object *in = lean_mk_string(req);   /* we own `in`                    */
  lean_object *res = tm_kernel_call(in);   /* consumed `in`, we own `res`    */
  const char *s = lean_string_cstr(res);
  char *out = strdup(s);
  lean_dec_ref(res);
  return out;
}

void tm_kernel_free(char *p) { free(p); }
